/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Toolkit;
import java.io.FileInputStream;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

/**
 * Home.java
 *
 * Created on 20 Oct, 2016, 10:37:05 AM
 */

/**
 *
 * @author Dewesh
 */
public class Home extends javax.swing.JFrame   {

    /** Creates new form Home */
    public Home() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HEADING = new javax.swing.JLabel();
        TRAIN_FILE = new javax.swing.JLabel();
        TEST_FILE = new javax.swing.JLabel();
        BTN_TRAIN_BROWSE = new javax.swing.JButton();
        BTN_TEST_BROWSE = new javax.swing.JButton();
        TXT_FLD_TRAIN = new javax.swing.JTextField();
        TXT_FLD_TEST = new javax.swing.JTextField();
        BTN_JUNCTION_TREE = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jta2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jta3 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        BTN_NB = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtaNB = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        NB_RESULT = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAMixed = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAMixed1 = new javax.swing.JTextArea();
        MixedBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Framework for NIDS");
        setBackground(new java.awt.Color(255, 255, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 51, 51));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ids-eye.png")));
        setResizable(false);

        HEADING.setFont(new java.awt.Font("Times New Roman", 1, 24));
        HEADING.setText("NETWORK INTRUSION DETECTION SYSTEM");

        TRAIN_FILE.setText("TRAINING DATSET");

        TEST_FILE.setText("TESTING DATASET");

        BTN_TRAIN_BROWSE.setText("BROWSE");
        BTN_TRAIN_BROWSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_TRAIN_BROWSEActionPerformed(evt);
            }
        });

        BTN_TEST_BROWSE.setText("BROWSE");
        BTN_TEST_BROWSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_TEST_BROWSEActionPerformed(evt);
            }
        });

        BTN_JUNCTION_TREE.setText("Decision Tree");
        BTN_JUNCTION_TREE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_JUNCTION_TREEActionPerformed(evt);
            }
        });

        jta2.setColumns(20);
        jta2.setEditable(false);
        jta2.setRows(5);
        jScrollPane3.setViewportView(jta2);

        jta3.setColumns(20);
        jta3.setEditable(false);
        jta3.setRows(5);
        jScrollPane4.setViewportView(jta3);

        jLabel1.setText("RESULTS SUMMARY");

        BTN_NB.setText("NB");
        BTN_NB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_NBActionPerformed(evt);
            }
        });

        jtaNB.setColumns(20);
        jtaNB.setRows(5);
        jScrollPane5.setViewportView(jtaNB);

        jLabel2.setText("RESULTS SUMMARY");

        NB_RESULT.setColumns(20);
        NB_RESULT.setRows(5);
        jScrollPane6.setViewportView(NB_RESULT);

        jTAMixed.setColumns(20);
        jTAMixed.setRows(5);
        jScrollPane1.setViewportView(jTAMixed);

        jTAMixed1.setColumns(20);
        jTAMixed1.setRows(5);
        jScrollPane2.setViewportView(jTAMixed1);

        MixedBTN.setText("Mixed");
        MixedBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MixedBTNActionPerformed(evt);
            }
        });

        jLabel3.setText("RESULTS SUMMARY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TRAIN_FILE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BTN_JUNCTION_TREE)
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(BTN_NB)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                .addComponent(jScrollPane6)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TEST_FILE)
                                .addComponent(TXT_FLD_TEST, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                                .addComponent(TXT_FLD_TRAIN, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BTN_TEST_BROWSE)
                                .addComponent(BTN_TRAIN_BROWSE))))
                    .addComponent(HEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                        .addComponent(MixedBTN)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TRAIN_FILE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT_FLD_TRAIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_TRAIN_BROWSE))
                        .addGap(14, 14, 14)
                        .addComponent(TEST_FILE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT_FLD_TEST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_TEST_BROWSE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTN_JUNCTION_TREE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTN_NB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MixedBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_JUNCTION_TREEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_JUNCTION_TREEActionPerformed
        // TODO add your handling code here:
         try{
            JunTreeConn jc=new JunTreeConn();
            jc.init(trainpath, testpath, jta2, jta3);
            jc.run();
            BTN_JUNCTION_TREE.setEnabled(false);
        }
        catch(Exception e){
            e.printStackTrace();
        }
         BTN_JUNCTION_TREE.setEnabled(false);
    }//GEN-LAST:event_BTN_JUNCTION_TREEActionPerformed

    private void BTN_TRAIN_BROWSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_TRAIN_BROWSEActionPerformed
        // TODO add your handling code here:
        trainpath = browse();
        TXT_FLD_TRAIN.setText(trainpath);
        
        BTN_TRAIN_BROWSE.setEnabled(false);
    }//GEN-LAST:event_BTN_TRAIN_BROWSEActionPerformed

    private void BTN_TEST_BROWSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_TEST_BROWSEActionPerformed
        // TODO add your handling code here:
        testpath=browse();
        TXT_FLD_TEST.setText(testpath);
        BTN_TEST_BROWSE.setEnabled(false);
    }//GEN-LAST:event_BTN_TEST_BROWSEActionPerformed

    private void BTN_NBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NBActionPerformed
        // TODO add your handling code here:
        try{
            NB nb=new NB();
            nb.init(trainpath, testpath, jtaNB, NB_RESULT);
            nb.run();
            BTN_NB.setEnabled(false);
        }
        catch(Exception e){
            e.printStackTrace();
        }
         BTN_NB.setEnabled(false);
    }//GEN-LAST:event_BTN_NBActionPerformed

    private void MixedBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MixedBTNActionPerformed
        // TODO add your handling code here:
        try{
            Compare cmp=new Compare();
            cmp.init(trainpath, testpath, jTAMixed, jTAMixed1 );
            cmp.run();
            MixedBTN.setEnabled(false);
        }
        catch(Exception e){
            e.printStackTrace();
        }
         MixedBTN.setEnabled(false);
    }//GEN-LAST:event_MixedBTNActionPerformed

    private String browse(){
        String path=new String();
        JFileChooser jfr = new JFileChooser();
	int check = jfr.showOpenDialog(this);
        if(check==JFileChooser.APPROVE_OPTION){
            path=jfr.getSelectedFile().getPath();
        }
        return path;
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    String testpath;
    String trainpath;
    NB nb=new NB();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_JUNCTION_TREE;
    private javax.swing.JButton BTN_NB;
    private javax.swing.JButton BTN_TEST_BROWSE;
    private javax.swing.JButton BTN_TRAIN_BROWSE;
    private javax.swing.JLabel HEADING;
    private javax.swing.JButton MixedBTN;
    private javax.swing.JTextArea NB_RESULT;
    private javax.swing.JLabel TEST_FILE;
    private javax.swing.JLabel TRAIN_FILE;
    private javax.swing.JTextField TXT_FLD_TEST;
    private javax.swing.JTextField TXT_FLD_TRAIN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTAMixed;
    private javax.swing.JTextArea jTAMixed1;
    private javax.swing.JTextArea jta2;
    private javax.swing.JTextArea jta3;
    private javax.swing.JTextArea jtaNB;
    // End of variables declaration//GEN-END:variables

}
